### ISSUE TITLE
Remove the widget when the countdown is at 0 and allow not to enter any data.

### ISSUE THREAD

**Issue by IkiaeM** [samerton/Nameless-Countdown#5]
Remove the widget when the countdown is at 0.
And allow not to enter any data in the countdown to not display the widget, without having to disable it in the widget section.

**Comment by Lukeos11** [comment]
I think this is a great idea but I don't think removing it when the countdown is at 0 it should be when there is no data in the settings/config for the module, in the meantime you can just set the count down to be no count down and set the time to be 5 seconds!

**Comment by IkiaeM** [comment]
Add a "remove" button on the "Countdown" page that will remove all ROW in the Countdown table. This removes the countdown and is quite simple in principle.

**Comment by samerton** [comment]
Thanks for the suggestion, added in the latest module release (commit 256ccc4f49507d9fc8f1df4582c0656308c3e8de)
